# FG1 - Configuración relevante (sanitizada)
# FortiOS 7.0.9
# Secretos omitidos para repositorio público.

config system interface
    edit "port1"
        set ip 192.168.200.2 255.255.255.0
        set allowaccess ping http https
    next
    edit "port3"
        set ip 203.0.113.157 255.255.255.252
        set allowaccess ping
        set alias "WAN-FG1"
        set role wan
    next
    edit "VLAN10-USERS"
        set ip 10.15.71.1 255.255.255.128
        set allowaccess ping
        set role lan
        set interface "port2"
        set vlanid 10
    next
    edit "VPN-FG1-FG2"
        set type tunnel
        set interface "port3"
    next
end

config system dhcp server
    edit 2
        set default-gateway 10.15.71.1
        set netmask 255.255.255.128
        set interface "VLAN10-USERS"
        config ip-range
            edit 1
                set start-ip 10.15.71.2
                set end-ip 10.15.71.126
            next
        end
        set dns-server1 8.8.8.8
    next
end

config firewall address
    edit "VPN-FG1-FG2_local_subnet_1"
        set allow-routing enable
        set subnet 10.15.71.0 255.255.255.128
    next
    edit "VPN-FG1-FG2_remote_subnet_1"
        set allow-routing enable
        set subnet 10.15.71.128 255.255.255.240
    next
end

config router static
    edit 1
        set gateway 203.0.113.158
        set device "port3"
    next
    edit 2
        set device "VPN-FG1-FG2"
        set dstaddr "VPN-FG1-FG2_remote"
    next
end

config vpn ipsec phase1-interface
    edit "VPN-FG1-FG2"
        set interface "port3"
        set peertype any
        set net-device disable
        set proposal des-md5 des-sha1
        set wizard-type static-fortigate
        set remote-gw 198.51.100.158
        set psksecret <REDACTED>
    next
end

config vpn ipsec phase2-interface
    edit "VPN-FG1-FG2"
        set phase1name "VPN-FG1-FG2"
        set proposal des-md5 des-sha1
        set src-name "VPN-FG1-FG2_local"
        set dst-name "VPN-FG1-FG2_remote"
    next
end

config firewall policy
    edit 1
        set name "USERS-to-WAN-NAT"
        set srcintf "VLAN10-USERS"
        set dstintf "port3"
        set action accept
        set srcaddr "all"
        set dstaddr "all"
        set schedule "always"
        set service "ALL"
        set nat enable
    next
    edit 2
        set name "vpn_VPN-FG1-FG2_local_0"
        set srcintf "VLAN10-USERS"
        set dstintf "VPN-FG1-FG2"
        set action accept
        set srcaddr "VPN-FG1-FG2_local"
        set dstaddr "VPN-FG1-FG2_remote"
        set schedule "always"
        set service "ALL"
    next
    edit 3
        set name "vpn_VPN-FG1-FG2_remote_0"
        set srcintf "VPN-FG1-FG2"
        set dstintf "VLAN10-USERS"
        set action accept
        set srcaddr "VPN-FG1-FG2_remote"
        set dstaddr "VPN-FG1-FG2_local"
        set schedule "always"
        set service "ALL"
    next
end
