# FG2 - Configuración relevante (sanitizada)
# FortiOS 7.0.9

config system interface
    edit "port1"
        set ip 192.168.200.3 255.255.255.0
        set allowaccess ping http https
    next
    edit "port2"
        set ip 10.15.71.129 255.255.255.240
        set allowaccess ping
        set role lan
    next
    edit "port3"
        set ip 198.51.100.158 255.255.255.252
        set allowaccess ping
        set role wan
    next
    edit "VPN-FG2-FG1"
        set type tunnel
        set interface "port3"
    next
end

config router static
    edit 1
        set gateway 198.51.100.157
        set device "port3"
    next
    edit 2
        set device "VPN-FG2-FG1"
        set dstaddr "VPN-FG2-FG1_remote"
    next
end

config vpn ipsec phase1-interface
    edit "VPN-FG2-FG1"
        set interface "port3"
        set peertype any
        set net-device disable
        set proposal des-md5 des-sha1
        set wizard-type static-fortigate
        set remote-gw 203.0.113.157
        set psksecret <REDACTED>
    next
end

config vpn ipsec phase2-interface
    edit "VPN-FG2-FG1"
        set phase1name "VPN-FG2-FG1"
        set proposal des-md5 des-sha1
        set src-name "VPN-FG2-FG1_local"
        set dst-name "VPN-FG2-FG1_remote"
    next
end

config firewall policy
    edit 1
        set name "SERVER-to-WAN-NAT"
        set srcintf "port2"
        set dstintf "port3"
        set action accept
        set srcaddr "all"
        set dstaddr "all"
        set schedule "always"
        set service "ALL"
        set nat enable
    next
    edit 2
        set name "vpn_VPN-FG2-FG1_local_0"
        set srcintf "port2"
        set dstintf "VPN-FG2-FG1"
        set action accept
        set srcaddr "VPN-FG2-FG1_local"
        set dstaddr "VPN-FG2-FG1_remote"
        set schedule "always"
        set service "ALL"
    next
    edit 3
        set name "vpn_VPN-FG2-FG1_remote_0"
        set srcintf "VPN-FG2-FG1"
        set dstintf "port2"
        set action accept
        set srcaddr "VPN-FG2-FG1_remote"
        set dstaddr "VPN-FG2-FG1_local"
        set schedule "always"
        set service "ALL"
    next
end
